on:
  push:
    branches:
    - "main"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - '2.x'

        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        path: "figuro"
    - name: Move
      run: |
        cd ../
        mv fig_ws/ figuro
        mkdir fig_ws/
        mv figuro/ fig_ws/figuro
        pwd
        find . | grep -v .git
    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Atlas
      run: |
        nim -v
        nimble -v
        nimble install 'https://github.com/nim-lang/atlas@#head'

    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: |
          vendor/
        key: ${{ runner.os }}-${{ hashFiles('atlas.lock') }}

    - name: Install Deps
      run: |
        # new atlas workspace
        atlas init --deps=vendor

        # sync deps
        atlas replay --cfgHere --ignoreUrls figuro/atlas.lock

    - name: Files
      run: |
        find . -depth 3 -type d | grep -v .git

    - name: Build Tests
      run: |
        nim test
