on:
  pull_request:
    branches:
    - "*"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - '2.x'
        os:
          - ubuntu-latest
    steps:
    # - uses: actions/checkout@v1
    #   with:
    #     path: "fig_ws/"
    - name: Clone Figuro
      run: |
        git clone https://github.com/elcritch/figuro.git figuro
        git -C figuro checkout $GITHUB_SHA

    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Files
      run: |
        pwd
        find . -maxdepth 3 -type d | grep -v .git

    - name: Install Atlas
      run: |
        nim -v
        nimble -v
        nimble install 'https://github.com/nim-lang/atlas@#head'

    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: |
          vendor/
        key: ${{ runner.os }}-${{ hashFiles('atlas.lock') }}

    - name: Install Deps
      run: |
        # new atlas workspace
        atlas init --deps=vendor

        # sync deps
        atlas replay --cfgHere --ignoreUrls figuro-dev/atlas.lock

    - name: Build Tests
      run: |
        nim test
